#!/usr/bin/env python3
"""
Compile prompts/*.md into SQL for the acq.prompts registry.

    python3 scripts/load_prompts.py | psql -v ON_ERROR_STOP=1 -d zenvexa_acq

Each prompt file carries YAML-ish frontmatter and three sections:

    ---
    key: research_clinic
    version: v1
    purpose: RESEARCH
    temperature: 0.15
    active: true
    also_keys: alias_one, alias_two     # optional
    ---

    ## System
    ...
    ## User Template
    ...
    ## Response Schema
    ```json
    { ... }
    ```

No third-party dependencies: it emits SQL on stdout and lets psql do the work.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROMPT_DIR = ROOT / "prompts"


def sql_str(value: str) -> str:
    """Dollar-quote so prompt bodies containing quotes need no escaping."""
    tag = "p"
    while f"${tag}$" in value:
        tag += "p"
    return f"${tag}${value}${tag}$"


def parse_frontmatter(text: str):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise ValueError("missing frontmatter")
    meta, body = {}, m.group(1)
    key = None
    for line in body.split("\n"):
        if re.match(r"^\s+", line) and key:          # folded continuation
            meta[key] += " " + line.strip()
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        meta[key] = "" if val == ">" else val
    return meta, text[m.end():]


def section(body: str, heading: str) -> str:
    m = re.search(rf"^## {heading}\s*\n(.*?)(?=^## |\Z)", body, re.S | re.M)
    if not m:
        raise ValueError(f"missing section: ## {heading}")
    return m.group(1).strip()


def main() -> int:
    files = sorted(PROMPT_DIR.glob("*.md"))
    if not files:
        print("no prompt files found", file=sys.stderr)
        return 1

    print("-- Generated by scripts/load_prompts.py. Do not edit; edit prompts/*.md.")
    print("BEGIN;")
    print("SET search_path = acq, public;")

    loaded = 0
    for path in files:
        text = path.read_text()
        try:
            meta, body = parse_frontmatter(text)
            system = section(body, "System")
            template = section(body, "User Template")
            raw_schema = section(body, "Response Schema")
        except ValueError as exc:
            print(f"{path.name}: {exc}", file=sys.stderr)
            return 1

        fence = re.search(r"```json\s*\n(.*?)\n```", raw_schema, re.S)
        if not fence:
            print(f"{path.name}: response schema is not in a ```json fence", file=sys.stderr)
            return 1
        try:
            schema = json.loads(fence.group(1))
        except json.JSONDecodeError as exc:
            print(f"{path.name}: response schema is not valid JSON: {exc}", file=sys.stderr)
            return 1

        keys = [meta["key"]] + [
            k.strip() for k in meta.get("also_keys", "").split(",") if k.strip()
        ]
        version = meta.get("version", "v1")
        active = str(meta.get("active", "true")).lower() == "true"

        for key in keys:
            # Only one version per key may be active, so stand the others down first.
            if active:
                print(f"UPDATE acq.prompts SET active = false "
                      f"WHERE key = {sql_str(key)} AND version <> {sql_str(version)};")
            print(
                "INSERT INTO acq.prompts (key, version, purpose, system_prompt, "
                "user_template, response_schema, temperature, active, notes, source_file) VALUES ("
                f"{sql_str(key)}, {sql_str(version)}, {sql_str(meta.get('purpose','GENERAL'))}, "
                f"{sql_str(system)}, {sql_str(template)}, "
                f"{sql_str(json.dumps(schema))}::jsonb, "
                f"{float(meta.get('temperature', 0.2))}, {str(active).lower()}, "
                f"{sql_str(meta.get('notes',''))}, {sql_str(path.name)}"
                ") ON CONFLICT (key, version) DO UPDATE SET "
                "purpose = EXCLUDED.purpose, system_prompt = EXCLUDED.system_prompt, "
                "user_template = EXCLUDED.user_template, "
                "response_schema = EXCLUDED.response_schema, "
                "temperature = EXCLUDED.temperature, active = EXCLUDED.active, "
                "notes = EXCLUDED.notes, source_file = EXCLUDED.source_file, "
                "loaded_at = now();"
            )
            loaded += 1

    print("COMMIT;")
    print(f"-- {loaded} prompt registrations from {len(files)} files", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
